import type { Character, Item, Skill } from "@/types";

export const dummyCharacters: Character[] = [];

export const dummyItems: Item[] = [];

export const dummyGuides: Array<{
  id: string;
  title: string;
  category: string;
  content: string;
  thumbnail?: string;
}> = [];

export const dummySkills: Skill[] = [
  {
    id: "assassin-active-quick-slash",
    name: "빠른 베기",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격"],
    cooldown: 1,
    mpCost: 0,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 최대 4명의 적에게 404~434의 피해를 주고 정신력을 120만큼 회복합니다.",
    target: "시전자 전방 4인(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    tags: ["논타겟", "이동 가능"],
    specialization: [
      "정신력 회복 20% 증가",
      "피해의 7%를 생명력으로 흡수",
      "적중 시 다단 히트 50% 증가",
      "[잠금] 적중 시 [문양 폭발] 재시전 시간 1초 감소",
      "[잠금] 막기 및 회피를 무시하고 치명타로 적중",
    ],
  },
  {
    id: "assassin-active-beast-roar",
    name: "맹수의 포효",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격", "약화"],
    cooldown: 1,
    mpCost: 96,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 최대 4명의 적에게 539~579의 피해를 주고 문양 1개를 10초 동안 각인합니다. 그로기 게이지 피해량 2.",
    groggyGauge: 2,
    target: "시전자 전방 4인(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    tags: ["논타겟"],
    specialization: [
      "정신력 소모 20% 감소",
      "스킬 속도 20% 증가",
      "적중 대상 수가 적을수록 피해량 최대 12% 증가",
      "[잠금] 적중 시 [암습] 재시전 시간 1초 감소",
      "[잠금] [맹수의 후려치기] 사용 시 주변 대상을 끌어당김",
    ],
  },
  {
    id: "assassin-active-ambush",
    name: "암습",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격", "약화"],
    cooldown: 20,
    mpCost: 150,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상의 뒤편으로 이동하여 855~918의 피해를 주고 75% 확률로 4초 동안 회전시키며 기절 상태로 만듭니다. 그로기 게이지 피해량 10.",
    groggyGauge: 10,
    target: "단일 대상(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    specialization: [
      "기절 유지 시간 1초 증가",
      "적중 시 3초 동안 자신의 치명타 피해 증폭 50% 증가",
      "적중 시 50% 확률로 5초 동안 침묵",
      "[잠금] 적중 시 500의 정신력 피해",
      "[잠금] 광역 스킬로 변경",
    ],
  },
  {
    id: "assassin-active-surprise-attack",
    name: "기습",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격", "약화"],
    cooldown: 10,
    mpCost: 200,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 대상에게 1332~1424의 피해를 줍니다. 후방에서 공격할 경우 피해가 50% 증가하고 10초 동안 문양 2개를 각인합니다. 그로기 게이지 피해량 7.",
    groggyGauge: 7,
    target: "단일 대상(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    specialization: [
      "후방 적중 시 10초 동안 문양 2개 각인",
      "피해의 30%를 생명력으로 흡수",
      "스킬 속도 20% 증가",
      "[잠금] 적중 시 50% 확률로 [회오리 베기] 활성화",
      "[잠금] 연속 시전 +3회",
    ],
  },
  {
    id: "assassin-active-flash-slash",
    name: "섬광 베기",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격", "약화"],
    cooldown: 10,
    mpCost: 50,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 대상의 반대쪽으로 이동하여 최대 4명의 적에게 1361~1444의 피해를 주고 50% 확률로 5초 동안 실명 상태로 만듭니다. 그로기 게이지 피해량 7.",
    groggyGauge: 7,
    target: "대상 주변 4인(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    specialization: [
      "실명 유지 시간 2초 증가",
      "사거리 6m 증가",
      "적중 대상 수가 많을수록 피해량 최대 20% 증가",
      "[잠금] 연속 시전 +2회",
      "[잠금] 실명 대상 적중 시 50% 확률로 3초 동안 회전",
    ],
  },
  {
    id: "assassin-active-glyph-explosion",
    name: "문양 폭발",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격", "약화"],
    cooldown: 10,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상을 중심으로 4m 내의 최대 4명의 적에게 1501~1586의 피해를 주고 3초 동안 회전시키며 기절 상태로 만듭니다. 문양 중첩 수에 따라 기절 확률이 증가합니다.",
    groggyGauge: 7,
    target: "대상 주변 4인(적대)",
    area: "4m",
    weaponRequirement: "단검",
    tags: ["이동 가능"],
    specialization: [
      "회전 효과 추가",
      "적중 시 다단 히트 50% 증가",
      "[문양 폭발] 후 문양 2중첩 각인 유지",
      "[잠금] 기절 유지 시간 1초 증가",
      "[잠금] 재시전 시간 5초 감소",
    ],
  },
  {
    id: "assassin-conditional-shadow-drop",
    name: "그림자 낙하",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "조건기",
    categories: ["물리", "공격", "약화"],
    cooldown: 20,
    mpCost: 100,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 기절 상태의 대상에게 2348~2485의 피해를 주고 피해의 30%만큼 생명력으로 흡수합니다. 적중 시 1.5초 동안 넘어짐 상태로 만듭니다.",
    target: "단일 대상(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    specialization: [
      "피해의 30% 생명력 흡수",
      "적중 시 문양 3개를 10초 동안 각인",
      "행동불가 면역 대상 공격 시 5% 확률로 활성화",
      "[잠금] 넘어짐 유지 시간 1초 증가",
      "[잠금] 광역 스킬로 변경",
    ],
  },
  {
    id: "assassin-conditional-rampage",
    name: "난무",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "조건기",
    categories: ["물리", "공격"],
    cooldown: 0,
    mpCost: 0,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 그로기 상태의 대상에게 896~956의 피해를 주고 피해의 10%만큼 생명력으로 흡수합니다.",
    target: "단일 대상(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    specialization: [
      "피해의 10% 생명력 흡수",
      "적중 시 정신력 120 회복",
      "이동 가능 스킬로 변경",
      "[잠금] 적중 시 확정 다단 히트",
      "[잠금] 적중 시 모든 스킬 재시전 시간 3초 감소",
    ],
  },
  {
    id: "assassin-conditional-heart-stab",
    name: "심장 찌르기",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "조건기",
    categories: ["물리", "공격"],
    cooldown: 5,
    mpCost: 100,
    range: 4,
    castTime: "즉시 시전",
    description:
      "치명타 적중 시 발동되며 4m 내 최대 4명의 적에게 1132~1211의 피해를 주고 피해의 20%만큼 생명력을 흡수합니다. 정신력을 100만큼 회복하며 그로기 게이지 피해량 5를 가합니다.",
    groggyGauge: 5,
    target: "시전자 전방 4인(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    specialization: [
      "피해의 20% 생명력 흡수",
      "적중 시 10초 동안 문양 1개 각인",
      "적중 대상 수가 적을수록 치명타 최대 20% 증가",
      "[잠금] 이동 가능 스킬로 변경",
      "[잠금] 치명타 적중 시 재시전 시간 초기화",
    ],
  },
  {
    id: "assassin-conditional-impact-release",
    name: "충격 해제",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "조건기",
    categories: ["강화"],
    cooldown: 51,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "자신의 기절, 넘어짐, 공중 속박 상태를 해제하고 5초 동안 강인함 상태가 됩니다. 강인함: 해당 상태 저항 100%, 피해 내성 20% 증가.",
    target: "시전자",
    weaponRequirement: "단검",
    tags: ["논타겟"],
    specialization: [
      "강인함 유지 시간 동안 피해 내성 20% 증가",
      "강인함 유지 시간 동안 피해 반사 10%",
      "[잠금] 시전 시 생명력 20% 회복",
      "[잠금] 강인함 유지 시간 2초 증가",
      "[잠금] 시전 시 25% 확률로 재시전 시간 초기화",
    ],
  },
  {
    id: "assassin-conditional-infiltration",
    name: "침투",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "조건기",
    categories: ["물리", "공격", "약화"],
    cooldown: 20,
    mpCost: 0,
    range: 10,
    castTime: "즉시 시전",
    description:
      "[긴급 회피] 사용 후 10m 내 대상의 뒤편으로 이동하여 1392~1474의 피해를 주고 50% 확률로 3초 동안 실명 상태로 만듭니다. 행동력을 300만큼 회복합니다.",
    groggyGauge: 10,
    target: "단일 대상(적대)",
    weaponRequirement: "단검",
    specialization: [
      "[침투] 적중 시 행동력 300 회복",
      "[침투] 사거리 10m 증가",
      "[침투] 적중 시 보호막 파괴",
      "[잠금] 2번 연속기 [암격] 추가",
      "[잠금] 실명 확률 25% 증가",
    ],
  },
  {
    id: "assassin-conditional-whirlwind-slash",
    name: "회오리 베기",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "조건기",
    categories: ["물리", "공격", "약화"],
    cooldown: 10,
    mpCost: 0,
    range: 4,
    castTime: "즉시 시전",
    description:
      "회피 성공 시 4m 내 대상에게 2049~2173의 피해를 주고 50% 확률로 3초 동안 회전시키며 기절 상태로 만듭니다. 다단 히트 적중률이 50% 증가합니다.",
    groggyGauge: 7,
    target: "단일 대상(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    specialization: [
      "적중 시 다단 히트 50% 증가",
      "광역 피해로 변경",
      "사거리 16m 증가",
      "[잠금] 기절 확률 25% 증가",
      "[잠금] 회피 시 50% 확률로 재시전 시간 초기화",
    ],
  },
  {
    id: "assassin-passive-ambush-stance",
    name: "기습 자세",
    class: "살성",
    level: 10,
    type: "공격",
    usageType: "패시브",
    categories: ["물리", "공격"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "실명 상태의 대상에게 공격을 적중시킬 때마다 50% 확률로 496~523의 피해를 줍니다.",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-passive-determination",
    name: "각오",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "생명력이 19% 이하인 대상에게 공격을 적중시킬 때마다 442~464의 피해를 줍니다.",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-passive-assault-stance",
    name: "강습 자세",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 0,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "자신의 치명타 피해 증폭이 15%만큼 증가합니다.",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-passive-shock-accuracy",
    name: "충격 적중",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 0,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "자신의 충격계 적중이 40%만큼 증가합니다.",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-passive-sixth-sense",
    name: "육감 극대화",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "회피가 200, 최대 생명력이 15% 증가하고 회피 성공 시 생명력을 432~518만큼 회복합니다.",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-passive-poison-coat",
    name: "독 바르기",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "공격이 적중할 때마다 7% 확률로 5초 동안 대상의 받는 회복량을 20% 감소시키고 1초마다 175~186의 지속 피해를 주는 중독 상태로 만듭니다.",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-passive-armor-rend",
    name: "방어 균열",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 10,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "그로기 또는 충격계 상태의 대상에게 공격을 적중시킬 때마다 5초 동안 대상의 방어력을 30% 감소시킵니다.",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-passive-backstab",
    name: "배후 강타",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 0,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "후방 피해 증폭이 15% 증가합니다.",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-passive-opening",
    name: "빈틈 노리기",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "치명타가 190 증가하고 치명타 적중 시 2.85% 확률로 최대 5명의 분신을 소환하여 각 149~159의 피해를 주며 10초 동안 유지되는 문양을 부여합니다. (최대 5회 중첩)",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-passive-life-contract",
    name: "회생의 계약",
    class: "살성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 60,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "생명력이 10% 이하일 때 생명력을 4000~4800만큼 즉시 회복합니다.",
    target: "시전자",
    weaponRequirement: "단검",
  },
  {
    id: "assassin-stigma-aerial-bind",
    name: "공중 포박",
    class: "살성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화"],
    cooldown: 120,
    mpCost: 150,
    range: 10,
    castTime: "즉시 시전",
    description:
      "10m 내 대상에게 1527~1617의 피해를 주고 50% 확률로 3초 동안 공중 속박 상태로 만듭니다. 문양 5중첩 대상에게는 100% 확률로 3초 동안 공중 속박 상태를 부여합니다.",
    groggyGauge: 20,
    target: "단일 대상(적대)",
    weaponRequirement: "단검",
    specialization: [
      "사거리 6m 증가",
      "[잠금] 2번 연속기 [공중 살법] 추가",
      "[잠금] 첫 타 적중 시 10초 동안 [기습 자세] 효과",
      "[잠금] 재시전 시간 30초 감소",
    ],
  },
  {
    id: "assassin-stigma-shadow-walk",
    name: "그림자 보행",
    class: "살성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["마법", "강화"],
    cooldown: 108,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "10초 동안 은신 상태가 됩니다. 은신 중 공격 시 확정 치명타로 적중합니다. 전투 상태에서는 사용할 수 없으며 사용 중 전투 상태가 되면 효과가 해제됩니다.",
    target: "시전자",
    weaponRequirement: "단검",
    tags: ["이동 가능"],
    specialization: [
      "은신 중 공격 시 확정 치명타",
      "[잠금] 유지 시간 동안 이동 속도 20% 증가",
      "[잠금] 전투 상태에서 사용 가능",
      "[잠금] 파티원에게 은신 부여",
    ],
  },
  {
    id: "assassin-stigma-assault-strike",
    name: "강습 습격",
    class: "살성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화", "강화"],
    cooldown: 120,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상을 중심으로 4m 내 최대 4명의 적에게 2316~2456의 피해를 주고 30% 확률로 5초 동안 실명 상태로 만듭니다. 적중 시 5초 동안 공격력이 20% 증가하며, 적중 인원 수에 비례해 방어력이 최대 20% 증가합니다.",
    target: "대상 주변 4인(적대)",
    weaponRequirement: "단검",
    tags: ["활강 전용"],
    specialization: [
      "적중 시 5초 동안 공격력 20% 증가",
      "[잠금] 적중 시 정신력 500 피해",
      "[잠금] 사거리 10m 증가",
      "[잠금] 실명 확률 20% 증가",
    ],
  },
  {
    id: "assassin-stigma-spiral-slash",
    name: "나선 베기",
    class: "살성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화"],
    cooldown: 90,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상에게 돌진하여 최대 4명의 적에게 3182~3375의 피해를 주고 50% 확률로 3초 동안 회전시키며 기절 상태로 만듭니다. 확정 치명타로 적중합니다.",
    groggyGauge: 20,
    target: "시전자 전방 4인(적대)",
    weaponRequirement: "단검",
    specialization: [
      "적중 시 확정 치명타",
      "[잠금] 적중 5초 동안 방어력 20% 감소",
      "[잠금] 기절 유지 시간 1초 증가",
      "[잠금] 기절 확률 25% 증가",
    ],
  },
  {
    id: "assassin-stigma-beast-fang",
    name: "맹수의 송곳니",
    class: "살성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화"],
    cooldown: 60,
    mpCost: 200,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 최대 4명의 적에게 2670~3237의 피해를 주고 문양 5개를 10초 동안 각인합니다.",
    groggyGauge: 50,
    target: "시전자 전방 4인(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    tags: ["논타겟"],
    specialization: [
      "적중 대상 수가 많을수록 피해량 최대 20% 증가",
      "[잠금] 주변 대상을 끌어당김",
      "[잠금] 적중 시 5초 동안 방어력 20% 감소",
      "[잠금] 치명타 시 25% 확률로 [문양 폭발] 연계 발동",
    ],
  },
  {
    id: "assassin-stigma-swift-contract",
    name: "신속의 계약",
    class: "살성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["마법", "강화"],
    cooldown: 60,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "12초 동안 전투 속도가 20% 증가하고 정신력 소모량이 20% 감소합니다.",
    target: "시전자",
    weaponRequirement: "단검",
    tags: ["이동 가능"],
    specialization: [
      "유지 시간 동안 정신력 소모량 20% 감소",
      "[잠금] 유지 시간 동안 [배후 강타] 효과 1.5배",
      "[잠금] 유지 시간 동안 [강습 자세] 효과 1.5배",
      "[잠금] 전투 속도 증가량 10% 추가",
    ],
  },
  {
    id: "assassin-stigma-shadow-dagger",
    name: "암검 투척",
    class: "살성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격"],
    cooldown: 30,
    mpCost: 100,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상에게 2290~2429의 피해를 주고 5초 동안 이동 속도를 40% 감소시키는 둔화 상태로 만듭니다. 적중 시 보호막을 파괴합니다.",
    groggyGauge: 15,
    target: "단일 대상(적대)",
    weaponRequirement: "단검",
    tags: ["이동 가능"],
    specialization: [
      "적중 시 보호막 파괴",
      "[잠금] 보호막 파괴 시 5초 동안 이동 속도 20% 증가",
      "[잠금] 적중 시 75% 확률로 3초 동안 실명",
      "[잠금] 보호막 파괴 시 재시전 시간 감소",
    ],
  },
  {
    id: "assassin-stigma-smoke-bomb",
    name: "연막탄",
    class: "살성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["마법", "강화"],
    cooldown: 82,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "5초 동안 유지되는 연막탄을 터뜨립니다. 연막 안에서 자신과 파티원들은 투사체에 피격되지 않고 회피가 200만큼 증가합니다.",
    target: "시전자",
    weaponRequirement: "단검",
    tags: ["이동 가능"],
    specialization: [
      "영역 내 파티원의 회피 200 증가",
      "[잠금] 영역 내 파티원의 육체 저항 20% 증가",
      "[잠금] 영역 내 파티원의 충격계 저항 20% 증가",
      "[잠금] 연막탄 유지 시간 2초 증가",
    ],
  },
  {
    id: "assassin-stigma-evasion-contract",
    name: "회피의 계약",
    class: "살성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["마법", "강화"],
    cooldown: 90,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "자신에게 걸린 둔화, 속박 효과를 해제하고 12초 동안 회피가 200 증가하며 둔화 면역 상태가 됩니다.",
    target: "시전자",
    weaponRequirement: "단검",
    tags: ["이동 가능"],
    specialization: [
      "유지 시간 동안 둔화 면역",
      "[잠금] 유지 시간 동안 이동 속도 20% 증가",
      "[잠금] 유지 시간 동안 속박 면역 효과 추가",
      "[잠금] 유지 시간 동안 [육감 극대화] 효과 1.5배 적용",
    ],
  },
  {
    id: "assassin-stigma-evasion-stance",
    name: "회피 자세",
    class: "살성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["물리", "강화"],
    cooldown: 20,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "잠시 동안 모든 피해를 확정 회피합니다. 연속으로 최대 2회까지 시전 가능하며 회피 성공 시 정신력과 행동력을 150만큼 회복합니다.",
    target: "시전자",
    weaponRequirement: "단검",
    tags: ["유지형"],
    specialization: [
      "연속 시전 +1회",
      "[잠금] 이동 가능 스킬로 변경",
      "[잠금] 연속 시전 +1회 추가",
      "[잠금] 회피 성공 시 생명력 10% 회복",
    ],
  },
  {
    id: "assassin-stigma-triniels-dagger",
    name: "트리니엘의 비수",
    class: "살성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화"],
    cooldown: 60,
    mpCost: 200,
    range: 4,
    castTime: "즉시 시전",
    description:
      "4m 내 대상에게 2825~2996의 피해를 주고 모든 스킬의 재시전 시간을 10%만큼 발생시킵니다. 대상의 후방에서 공격할 경우 피해가 50% 증가합니다.",
    groggyGauge: 20,
    target: "단일 대상(적대)",
    area: "5x5m",
    weaponRequirement: "단검",
    tags: ["논타겟", "이동 가능"],
    specialization: [
      "이동 가능 스킬로 변경",
      "[잠금] 모든 스킬의 재시전 시간 발생량 10% 증가",
      "[잠금] 적중 시 모든 스킬 재시전 시간 20% 감소",
      "[잠금] 적 처치 시 재시전 시간 초기화",
    ],
  },
  {
    id: "assassin-stigma-spectral-clones",
    name: "환영 분신",
    class: "살성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["마법", "강화"],
    cooldown: 120,
    mpCost: 200,
    range: 0,
    castTime: "즉시 시전",
    description: "12초 동안 모든 공격의 30%만큼 추가 피해를 줍니다.",
    target: "시전자",
    weaponRequirement: "단검",
    tags: ["이동 가능"],
    specialization: [
      "추가 피해량 10% 증가",
      "[잠금] 유지 시간 동안 치명타 피해 증폭 20% 증가",
      "[잠금] 유지 시간 동안 [빈틈 노리기] 효과 1.5배 적용",
      "[잠금] 재시전 시간 30초 감소",
    ],
  },
  // 궁성 액티브 스킬
  {
    id: "ranger-active-snipe",
    name: "저격",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격"],
    cooldown: 1,
    mpCost: 50,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내의 대상에게 372~400의 피해를 주고 정신력을 144만큼 회복합니다.",
    target: "단일 대상(적대)",
    tags: ["이동 가능"],
    weaponRequirement: "활",
    specialization: [
      "정신력 회복 20% 증가",
      "피해의 7% 생명력 흡수",
      "적중 시 다단 히트 50% 증가",
      "[잠금] 적중 시 [조준 화살] 재시전 시간 1초 감소",
      "[잠금] 4번 연속기 [질풍 화살] 추가",
    ],
  },
  {
    id: "ranger-active-explosive-trap",
    name: "폭발의 덫",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격", "약화"],
    cooldown: 20,
    mpCost: 200,
    range: 0,
    castTime: "즉시 시전",
    description:
      "자신 근처에 범위형 함정을 설치합니다. 함정은 20초 동안 유지되며, 적이 접근하면 폭발하여 5m 내 최대 4명에게 피해를 주고 끌어당기며 기절 상태로 만듭니다.",
    target: "시전자 주변 4인(적대)",
    tags: ["설치형"],
    weaponRequirement: "활",
    specialization: [
      "폭발 시 적들을 끌어당김",
      "기절 유지 시간 1초 증가",
      "폭발 시 자연 피해 부여",
      "[잠금] 기절 확률 25% 증가",
      "[잠금] 충전형 스킬로 변경",
    ],
  },
  {
    id: "ranger-active-rapid-shot",
    name: "속사",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격"],
    cooldown: 0,
    mpCost: 96,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상을 중심으로 4m 내의 최대 4명의 적에게 522~562의 피해를 줍니다. 그로기 게이지 피해량 1.",
    groggyGauge: 1,
    target: "대상 주변 4인(적대)",
    area: "4m",
    tags: ["이동 가능"],
    weaponRequirement: "활",
    specialization: [
      "정신력 소모 20% 감소",
      "적중 시 치명타 10% 증가",
      "적중한 대상 수가 적을수록 피해량 최대 12% 증가",
      "[잠금] 적중 시 10% 밀려남 부여",
      "[잠금] 스킬 속도 20% 증가",
    ],
  },
  {
    id: "ranger-active-gale-arrow",
    name: "광풍 화살",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격"],
    cooldown: 20,
    mpCost: 200,
    range: 20,
    castTime: 0.5,
    description:
      "20m 내 대상을 중심으로 4m 내의 최대 4명의 적에게 1701~3306의 피해를 주는 차징 스킬입니다. 그로기 게이지 피해량 10.",
    groggyGauge: 10,
    target: "대상 주변 4인(적대)",
    area: "4m",
    tags: ["차지 스킬"],
    weaponRequirement: "활",
    specialization: [
      "적중한 대상 수가 많을수록 피해량 최대 20% 증가",
      "스킬 속도 30% 증가",
      "이동 가능 스킬로 변경",
      "[잠금] 적중 시 밀려남 부여",
      "[잠금] 재시전 시간 10초 감소",
    ],
  },
  {
    id: "ranger-active-aimed-shot",
    name: "조준 화살",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격"],
    cooldown: 20,
    mpCost: 200,
    range: 20,
    castTime: 0.5,
    description:
      "20m 내 대상에게 2410~4083의 피해를 줍니다. 대상이 표적 상태일 경우 피해가 25% 증가하며, 다단 히트 적중률이 50%만큼 증가합니다. 그로기 게이지 피해량 10.",
    groggyGauge: 10,
    target: "단일 대상(적대)",
    tags: ["차지 스킬"],
    weaponRequirement: "활",
    specialization: [
      "적중 시 다단 히트 50% 증가",
      "스킬 속도 30% 증가",
      "이동 가능 스킬로 변경",
      "[잠금] 최대 차지 시 막기 및 회피를 무시하고 치명타로 적중",
      "[잠금] 최대 차지 시 75% 확률로 3초 동안 기절",
    ],
  },
  {
    id: "ranger-active-snare-arrow",
    name: "올가미 화살",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격", "약화"],
    cooldown: 15,
    mpCost: 150,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상을 중심으로 4m 내의 최대 4명의 적에게 872~938의 피해를 주고 5초 동안 이동 속도를 60% 감소시키는 둔화 상태로 만듭니다. 그로기 게이지 피해량 10.",
    groggyGauge: 10,
    target: "대상 주변 4인(적대)",
    area: "4m",
    weaponRequirement: "활",
    specialization: [
      "[올가미 화살]의 이동 속도 감소량 20% 증가",
      "스킬 속도 20% 증가",
      "이동 가능 스킬로 변경",
      "[잠금] 2번 연속기 [즉폭 화살] 추가",
      "[잠금] 둔화 및 속박 유지 시간 2초 증가",
    ],
  },
  {
    id: "ranger-active-marked-shot",
    name: "표적 화살",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "액티브",
    categories: ["물리", "공격", "약화"],
    cooldown: 10,
    mpCost: 50,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상에게 1302~1394의 피해를 주고 자신은 입력 방향으로 이동합니다. 대상은 5초 동안 치명타 저항이 감소하고 방어력이 10% 감소하는 표적 상태가 됩니다. 그로기 게이지 피해량 7.",
    groggyGauge: 7,
    target: "단일 대상(적대)",
    weaponRequirement: "활",
    specialization: [
      "적중 시 방어력 10% 감소",
      "적중 시 75% 확률로 밀려남 부여",
      "표적 유지 시간 2초 증가",
      "[잠금] 충전형 스킬로 변경",
      "[잠금] 적중 시 정신력 300 피해",
    ],
  },
  // 궁성 스티그마 스킬
  {
    id: "ranger-stigma-baizels-might",
    name: "바이젤의 권능",
    class: "궁성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["마법", "강화"],
    cooldown: 60,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "12초 동안 자신의 공격력이 20%만큼 증가하고 적대치가 50%만큼 감소합니다.",
    target: "시전자",
    weaponRequirement: "활",
    specialization: [
      "유지 시간 동안 적대치 50% 감소",
      "유지 시간 동안 [집중 포화] 효과 1.5배 적용",
      "유지 시간 동안 [사냥꾼의 혼] 효과 1.5배 적용",
      "공격력 증가량 10% 추가 증가",
    ],
  },
  {
    id: "ranger-stigma-natures-veil",
    name: "대자연의 숨결",
    class: "궁성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["마법", "강화"],
    cooldown: 82,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "10초 동안 자신의 정신계 저항이 30%만큼 증가하고 적에게 받는 모든 마법 피해의 10%를 반사합니다. 이동 가능.",
    target: "시전자",
    weaponRequirement: "활",
    tags: ["이동 가능"],
    specialization: [
      "정신계 저항 30% 증가",
      "지속 피해 상태 해제",
      "지속 피해 면역 효과 추가",
      "마법 피해 반사 10% 추가 증가",
    ],
  },
  {
    id: "ranger-stigma-blessing-of-the-bow",
    name: "축복의 활",
    class: "궁성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["마법", "강화"],
    cooldown: 120,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "12초 동안 자신과 주변 40m 내 파티원의 치명타가 200 증가하고 다단 히트 적중률이 50% 증가합니다.",
    target: "시전자 주변 4인(파티원)",
    area: "40m",
    weaponRequirement: "활",
    specialization: [
      "유지 시간 동안 다단 히트 적중 50% 증가",
      "유지 시간 동안 명중 100 증가",
      "유지 시간 동안 치명타 피해 증폭 20% 증가",
      "유지 시간 동안 적 처치 시 모든 재시전 시간 5초 감소",
    ],
  },
  {
    id: "ranger-stigma-explosive-arrow",
    name: "폭발 화살",
    class: "궁성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화"],
    cooldown: 60,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상을 중심으로 4m 내 최대 4명의 적에게 3100~3294의 피해를 줍니다. 대상이 충격계 상태일 경우 피해가 20% 증가합니다.",
    groggyGauge: 20,
    target: "대상 주변 4인(적대)",
    area: "4m",
    weaponRequirement: "활",
    tags: ["이동 가능"],
    specialization: [
      "재시전 시간 30초 감소",
      "충격계 상태 대상 피해량 10% 추가 증가",
      "적중 시 확정 치명타",
      "충격계 상태 대상 피해량 20% 추가 증가",
    ],
  },
  {
    id: "ranger-stigma-griffon-arrow",
    name: "그리폰 화살",
    class: "궁성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화"],
    cooldown: 60,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "그리폰이 날아가는 경로 내 최대 4명의 적에게 2409~2559의 피해를 줍니다. 적들은 10초 동안 1초 간격으로 불 속성 지속 피해를 받습니다. 그로기 게이지 피해량 50.",
    groggyGauge: 50,
    target: "대상 주변 4인(적대)",
    area: "4m",
    weaponRequirement: "활",
    tags: ["이동 가능"],
    specialization: [
      "이동 가능 스킬로 변경",
      "지속 피해 유지 시간 5초 증가",
      "75% 확률로 대상을 밀려남",
      "지속 피해 간격 50% 감소",
    ],
  },
  {
    id: "ranger-stigma-binding-trap",
    name: "결박의 덫",
    class: "궁성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화"],
    cooldown: 90,
    mpCost: 200,
    range: 0,
    castTime: "즉시 시전",
    description:
      "자신 근처에 범위형 함정을 설치합니다. 함정은 1분 동안 유지되며, 적이 접근하면 5m 내 최대 4명에게 피해를 주고 3초 동안 공중 속박 상태로 만듭니다.",
    target: "시전자 주변 4인(적대)",
    area: "5m",
    weaponRequirement: "활",
    specialization: [
      "적중한 대상 수가 많을수록 피해량 최대 20% 증가",
      "적중 시 보호막 파괴",
      "공중 속박 유지 시간 1초 증가",
      "재시전 시간 30초 감소",
    ],
  },
  {
    id: "ranger-stigma-stealth",
    name: "은신",
    class: "궁성",
    level: 5,
    type: "강화",
    usageType: "스티그마",
    categories: ["마법", "강화"],
    cooldown: 108,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "10초 동안 은신 상태가 됩니다. 은신 중 공격은 반드시 치명타로 적중합니다. 전투 상태에서는 사용할 수 없으며, 은신 중 전투 상태가 되면 효과가 해제됩니다.",
    target: "시전자",
    weaponRequirement: "활",
    tags: ["이동 가능"],
    specialization: [
      "은신 중 공격 시 치명타",
      "유지 시간 동안 이동 속도 20% 증가",
      "전투 상태에서 사용 가능",
      "은신 유지 시간 10초 증가",
    ],
  },
  {
    id: "ranger-stigma-silence-arrow",
    name: "침묵 화살",
    class: "궁성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화"],
    cooldown: 90,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상에게 2607~2770의 피해를 주고 75% 확률로 5초 동안 침묵 상태로 만듭니다. 그로기 게이지 피해량 20.",
    groggyGauge: 20,
    target: "단일 대상(적대)",
    weaponRequirement: "활",
    tags: ["이동 가능"],
    specialization: [
      "이동 가능 스킬로 변경",
      "재시전 시간 30초 감소",
      "침묵 확률 25% 증가",
      "침묵 유지 시간 3초 증가",
    ],
  },
  {
    id: "ranger-stigma-arrow-storm",
    name: "화살 폭풍",
    class: "궁성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격", "약화"],
    cooldown: 90,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상을 중심으로 4m 내 최대 4명의 적에게 3107~3772의 피해를 주고 50% 확률로 3초 동안 기절 상태로 만듭니다. 그로기 게이지 피해량 20.",
    groggyGauge: 20,
    target: "대상 주변 4인(적대)",
    area: "4m",
    weaponRequirement: "활",
    specialization: [
      "적중한 대상 수가 많을수록 피해량 최대 20% 증가",
      "재시전 시간 30초 감소",
      "기절 유지 시간 1초 증가",
      "기절 확률 25% 증가",
    ],
  },
  {
    id: "ranger-stigma-surprise-kick",
    name: "기습 차기",
    class: "궁성",
    level: 5,
    type: "공격",
    usageType: "스티그마",
    categories: ["물리", "공격"],
    cooldown: 30,
    mpCost: 0,
    range: 10,
    castTime: "즉시 시전",
    description:
      "10m 내 대상의 뒤로 이동하여 2141~2275의 피해를 주고 밀려남 상태로 만듭니다. 자신은 후방으로 이동합니다.",
    target: "단일 대상(적대)",
    weaponRequirement: "활",
    specialization: [
      "사거리 5m 증가",
      "적중 시 5초 동안 최대 생명력의 10% 보호막",
      "적중 시 50% 확률로 3초 동안 기절",
      "기절 확률 50% 증가",
    ],
  },
  {
    id: "ranger-stigma-sleep-arrow",
    name: "수면 화살",
    class: "궁성",
    level: 5,
    type: "디버프",
    usageType: "스티그마",
    categories: ["물리", "약화"],
    cooldown: 82,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내 대상을 10초 동안 수면 상태로 만들고 방어력을 40% 감소시킵니다. 5회의 공격을 받으면 수면이 해제됩니다.",
    target: "단일 대상(적대)",
    weaponRequirement: "활",
    specialization: [
      "수면 해제를 위한 피격 횟수 증가",
      "수면 자연 종료 시 10초 동안 막기, 회피 감소",
      "수면 자연 종료 시 충격계 저항 20% 감소",
      "수면 일반 해제 시에도 약화 마법 부여",
    ],
  },
  // 궁성 조건기 스킬
  {
    id: "ranger-conditional-rupture-arrow",
    name: "파열 화살",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "조건기",
    categories: ["물리", "공격"],
    cooldown: 30,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내의 둔화, 속박 상태의 대상을 중심으로 4m 내 최대 4명의 적에게 1758~1864의 피해를 주고 피해의 20%만큼 생명력으로 흡수합니다. 그로기 게이지 피해량 15.",
    groggyGauge: 15,
    target: "단일 대상(적대)",
    area: "4m",
    weaponRequirement: "활",
    specialization: [
      "피해의 20% 생명력 흡수",
      "적중 시 다단 히트 50% 증가",
      "이동 가능 스킬로 변경",
      "5초 동안 지속 피해",
      "[파열 화살] 적중 시 25% 확률로 재시전 시간 30초 감소",
    ],
  },
  {
    id: "ranger-conditional-curved-shot",
    name: "곡사",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "조건기",
    categories: ["물리", "공격"],
    cooldown: 0,
    mpCost: 150,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내의 그로기 상태 대상에게 756~808의 피해를 주고 피해의 10%만큼 생명력으로 흡수합니다.",
    target: "단일 대상(적대)",
    weaponRequirement: "활",
    specialization: [
      "피해의 10% 생명력 흡수",
      "적중 시 정신력 120 회복",
      "이동 가능 스킬로 변경",
      "적중 시 확정 다단 히트",
      "적중 시 모든 스킬 재시전 시간 3초 감소",
    ],
  },
  {
    id: "ranger-conditional-impact-release",
    name: "충격 해제",
    class: "궁성",
    level: 10,
    type: "강화",
    usageType: "조건기",
    categories: ["강화"],
    cooldown: 51,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "자신의 기절, 넘어짐, 공중 속박 상태를 해제하고 5초 동안 강인함 상태가 됩니다. 강인함: 기절, 넘어짐, 공중 속박 저항 100%, 피해 내성 20% 증가.",
    target: "시전자",
    weaponRequirement: "활",
    specialization: [
      "강인함 유지 시간 동안 피해 내성 20% 증가",
      "강인함 유지 시간 동안 피해의 10%를 적에게 반사",
      "[충격 해제] 시전 시 생명력 20% 회복",
      "강인함 유지 시간 2초 증가",
      "[충격 해제] 시전 시 25% 확률로 재시전 시간 25% 감소",
    ],
  },
  {
    id: "ranger-conditional-suppressive-arrow",
    name: "제압 화살",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "조건기",
    categories: ["물리", "공격", "약화"],
    cooldown: 20,
    mpCost: 150,
    range: 20,
    castTime: "즉시 시전",
    description:
      "20m 내의 표적 상태 대상에게 1831~1941의 피해를 주고 50% 확률로 3초 동안 기절 상태로 만듭니다. 그로기 게이지 피해량 10.",
    groggyGauge: 10,
    target: "단일 대상(적대)",
    weaponRequirement: "활",
    specialization: [
      "적중 시 다단 히트 50% 증가",
      "기절 유지 시간 1초 증가",
      "스킬 속도 20% 증가",
      "기절 확률 25% 증가",
      "[제압 화살] 적중 시 25% 확률로 재시전 시간 10초 감소",
    ],
  },
  {
    id: "ranger-conditional-piercing-arrow",
    name: "송곳 화살",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "조건기",
    categories: ["물리", "공격", "약화"],
    cooldown: 5,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description:
      "치명타 적중 시 발동되며, 20m 내 대상을 중심으로 4m 내 최대 4명의 적에게 1004~1075의 피해를 주고 정신력을 100 회복합니다. 자신은 피해의 20%만큼 생명력으로 흡수하고 대상에게 6초 동안 출혈 상태를 부여합니다. 그로기 게이지 피해량 5.",
    groggyGauge: 5,
    target: "대상 주변 4인(적대)",
    area: "4m",
    weaponRequirement: "활",
    specialization: [
      "피해의 20% 생명력 흡수",
      "출혈 유지 시간 2초 증가",
      "이동 가능 스킬로 변경",
      "막기 및 회피를 무시하고 치명타로 적중",
      "[송곳 화살] 치명타 시 50% 확률로 재시전 시간 5초 감소",
    ],
  },
  // 궁성 패시브 스킬
  {
    id: "ranger-passive-vigilant-eye",
    name: "경계의 눈",
    class: "궁성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "자신의 회피가 200, 최대 생명력이 15% 증가하고 회피 성공 시 생명력을 432~518만큼 즉시 회복합니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
  {
    id: "ranger-passive-resolve-of-resistance",
    name: "저항의 결의",
    class: "궁성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 0,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "자신의 육체계 저항이 37%만큼 증가합니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
  {
    id: "ranger-passive-eye-of-focus",
    name: "집중의 눈",
    class: "궁성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 0,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "자신의 명중이 100 증가하고 공격력이 15%만큼 증가합니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
  {
    id: "ranger-passive-hunters-resolve",
    name: "사냥꾼의 결의",
    class: "궁성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 0,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "자신의 치명타 피해 증폭이 15%만큼 증가합니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
  {
    id: "ranger-passive-hunters-soul",
    name: "사냥꾼의 혼",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "패시브",
    categories: ["물리", "공격"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "치명타 시 50% 확률로 716~752의 추가 피해를 줍니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
  {
    id: "ranger-passive-full-barrage",
    name: "집중 포화",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "패시브",
    categories: ["물리", "공격"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "지속 피해를 입는 대상에게 50% 확률로 267~284의 추가 피해를 줍니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
  {
    id: "ranger-passive-close-quarters-shot",
    name: "근접 사격",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "패시브",
    categories: ["물리", "공격"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "10m 내의 대상에게 공격을 적중시킬 때마다 25% 확률로 401~422의 추가 피해를 줍니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
  {
    id: "ranger-passive-life-contract",
    name: "회생의 계약",
    class: "궁성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 60,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "자신의 생명력이 10% 이하일 때 생명력을 4000~4800만큼 즉시 회복합니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
  {
    id: "ranger-passive-winds-vigor",
    name: "바람의 활력",
    class: "궁성",
    level: 10,
    type: "강화",
    usageType: "패시브",
    categories: ["물리", "강화"],
    cooldown: 5,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "공격을 받을 때마다 1.8초 동안 이동 속도가 19% 증가합니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
  {
    id: "ranger-passive-eye-of-snare",
    name: "속박의 눈",
    class: "궁성",
    level: 10,
    type: "공격",
    usageType: "패시브",
    categories: ["물리", "공격", "약화"],
    cooldown: 1,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description:
      "치명타 시 5% 확률로 5초 동안 속박 상태로 만들고, 속박 상태 대상에게 공격을 적중시킬 때마다 50% 확률로 468~495의 피해를 줍니다.",
    target: "시전자",
    weaponRequirement: "활",
  },
];

