import type { Character, Item, Skill } from "@/types";

/**
 * 캐릭터 더미 데이터 (8가지 클래스)
 */
export const dummyCharacters: Character[] = [
  {
    id: "1",
    name: "검성",
    class: "검성",
    level: 65,
    stats: {
      hp: 15200,
      mp: 3200,
      attack: 1850,
      defense: 1420,
      accuracy: 890,
      evasion: 650,
    },
  },
  {
    id: "2",
    name: "수호성",
    class: "수호성",
    level: 65,
    stats: {
      hp: 14800,
      mp: 3800,
      attack: 1720,
      defense: 1580,
      accuracy: 850,
      evasion: 620,
    },
  },
  {
    id: "3",
    name: "살성",
    class: "살성",
    level: 65,
    stats: {
      hp: 11200,
      mp: 2800,
      attack: 1920,
      defense: 980,
      accuracy: 1120,
      evasion: 1420,
    },
  },
  {
    id: "4",
    name: "궁성",
    class: "궁성",
    level: 65,
    stats: {
      hp: 10800,
      mp: 3200,
      attack: 1880,
      defense: 920,
      accuracy: 1180,
      evasion: 1380,
    },
  },
  {
    id: "5",
    name: "마도성",
    class: "마도성",
    level: 65,
    stats: {
      hp: 9800,
      mp: 5200,
      attack: 1980,
      defense: 780,
      accuracy: 1120,
      evasion: 580,
    },
  },
  {
    id: "6",
    name: "정령성",
    class: "정령성",
    level: 65,
    stats: {
      hp: 10200,
      mp: 4800,
      attack: 1750,
      defense: 850,
      accuracy: 1080,
      evasion: 620,
    },
  },
  {
    id: "7",
    name: "호법성",
    class: "호법성",
    level: 65,
    stats: {
      hp: 10800,
      mp: 4800,
      attack: 1420,
      defense: 1020,
      accuracy: 980,
      evasion: 720,
    },
  },
  {
    id: "8",
    name: "치유성",
    class: "치유성",
    level: 65,
    stats: {
      hp: 11200,
      mp: 4200,
      attack: 1580,
      defense: 1180,
      accuracy: 920,
      evasion: 780,
    },
  },
];

/**
 * 스킬 더미 데이터
 */
export const dummySkills: Skill[] = [
  // 검성 스킬
  {
    id: "sword-1",
    name: "예리한 일격",
    class: "검성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 100,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 최대 4명의 적에게 499-500 피해를 입히고 위협도를 증가시킵니다. 명중 시 다중 크리티컬 확률이 50% 증가하고, [파멸의 맹타]의 재시전 시간이 1초 감소합니다. 정신력 120 회복.",
    groggyGauge: 0,
    tags: ["발동기"],
    target: "시전자 주변 4인(적대)",
    specialization: [
      "정신력 회복량 20% 증가",
      "피해의 7%를 HP로 흡수",
      "명중 시 다중 크리티컬 확률 50% 증가",
      "[파멸의 맹타] 명중 시 재시전 시간 1초 감소",
      "4타 연속 공격 [무모한 일격] 추가",
    ],
  },
  {
    id: "sword-2",
    name: "도약 찍기",
    class: "검성",
    level: 20,
    type: "공격",
    cooldown: 15,
    mpCost: 150,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상으로 도약하여 대상 주변 4m 내 최대 4명의 적을 끌어당기며 1654-1658 피해를 입힙니다. 50% 확률로 [발목 베기] 발동. 적 처치 시 [도약 찍기]의 재시전 시간이 초기화됩니다.",
    groggyGauge: 10,
    tags: [],
    target: "대상 주변 4인(적대)",
    specialization: [
      "3초간 '전투 준비' 효과 획득",
      "[도약 찍기] 명중 시 50% 확률로 [발목 베기] 발동",
      "적 처치 시 [도약 찍기]의 재시전 시간 초기화",
      "3초간 피해 저항력 20% 증가",
      "광역 스킬로 변경 및 적 끌어당김",
    ],
  },
  {
    id: "sword-3",
    name: "유린의 검",
    class: "검성",
    level: 20,
    type: "공격",
    element: undefined,
    cooldown: 20,
    mpCost: 200,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 대상에게 2403-2409 피해를 입히고 4초간 눕힙니다. 피해의 30%를 HP로 흡수합니다. 눕힐 때 대상 주변 4m 내 최대 4명의 적에게 피해를 입힙니다. 대상이 군중 제어 면역인 경우 연출이 변경됩니다.",
    groggyGauge: 15,
    tags: ["약화"],
    target: "단일 대상(적대)",
    specialization: [
      "피해의 30%를 HP로 흡수",
      "눕힐 때 광역 피해로 변경",
      "추가 공격 2회",
      "눕힘 지속 시간 1초 증가",
      "막기와 회피 무시, 다중 타격",
    ],
  },
  {
    id: "sword-4",
    name: "분쇄 파동",
    class: "검성",
    level: 20,
    type: "공격",
    cooldown: 20,
    mpCost: 250,
    range: 4,
    castTime: "즉시 시전",
    description: "시전자 주변 5m 내 최대 4명의 적을 끌어당기며 1652-1654 피해를 입힙니다. 피해의 15%를 HP로 흡수합니다. 크리티컬 발생 시 재시전 시간이 초기화됩니다.",
    groggyGauge: 5,
    tags: ["발동기"],
    target: "시전자 주변 4인(적대)",
    specialization: [
      "피해의 15%를 HP로 흡수",
      "크리티컬 시 정신력 50 회복",
      "명중 대상 수에 따라 최대 20%까지 피해 증가",
      "크리티컬 시 재시전 시간 초기화",
      "적 끌어당김",
    ],
  },
  {
    id: "sword-5",
    name: "파멸의 맹타",
    class: "검성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 250,
    range: 20,
    castTime: 0.5,
    description: "20m 내 대상에게 돌진하여 5411-5420 피해를 입히고, 시전자는 10초간 '전투 준비' 상태가 됩니다. 최대 차지 시 최대 4명의 적에게 피해를 입힙니다. 전투 준비: 피해 증폭 10% 증가, 크리티컬 100 증가.",
    groggyGauge: 15,
    tags: [],
    target: "단일 대상(적대)",
    specialization: [
      "스킬 속도 20% 증가",
      "사거리 12.5m 증가",
      "이동 가능 스킬로 변경",
      "전투 준비 지속 시간 5초 증가",
      "막기와 회피 무시, 다중 타격",
    ],
  },
  {
    id: "sword-6",
    name: "칼날 날리기",
    class: "검성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 0,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상에게 1579-1581 피해를 입히고 방어력 30% 감소(5초), 이동 속도 감소(5초), 보호막 파괴 효과를 적용합니다.",
    groggyGauge: 5,
    tags: ["약화", "발동기"],
    target: "단일 대상(적대)",
    specialization: [
      "[칼날 날리기] 추가 방어력 감소 10%",
      "[칼날 날리기] 이동 속도 감소 5초 적용",
      "[칼날 날리기] 보호막 파괴",
      "[칼날 화무] 30% 확률로 3초간 눕힘",
    ],
  },
  {
    id: "sword-7",
    name: "흡혈의 검",
    class: "검성",
    level: 20,
    type: "공격",
    cooldown: 60,
    mpCost: 200,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 대상을 위로 올려치며 1568-1570 피해를 입히고, 내려치며 대상과 주변 5x10m 내 최대 4명의 적에게 3050-3492 피해를 입힙니다. 피해의 50%를 HP로 흡수합니다.",
    groggyGauge: 20,
    tags: [],
    target: "단일 대상(적대)",
    specialization: [
      "명중 대상 수에 따라 최대 20%까지 피해 증가",
      "HP 흡수량 10% 증가",
      "재시전 시간 30초 감소",
      "HP 흡수량 20% 증가",
    ],
  },
  {
    id: "sword-8",
    name: "분노의 파동",
    class: "검성",
    level: 20,
    type: "공격",
    cooldown: 60,
    mpCost: 200,
    range: 4,
    castTime: "즉시 시전",
    description: "시전자 주변 5m 내 최대 4명의 적에게 2회에 걸쳐 3316-3796 피해를 입히고, 적의 공격력 20% 감소(5초), 3초간 눕힘 효과를 적용합니다.",
    groggyGauge: 50,
    tags: ["약화"],
    target: "시전자 주변 4인(적대)",
    specialization: [
      "명중 대상 수에 따라 최대 20%까지 피해 증가",
      "5초간 공격력 20% 감소 적용",
      "추가 공격 1회",
      "눕힘 확률 25% 증가",
    ],
  },
  {
    id: "sword-9",
    name: "격노 폭발",
    class: "검성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 100,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내 대상에게 3920-3925 피해를 입히고 항상 크리티컬로 명중합니다. 대상이 '중격계' 상태인 경우 피해가 50% 증가합니다.",
    groggyGauge: 20,
    tags: [],
    target: "단일 대상",
    specialization: [
      "[격노 폭발] 재시전 시간 15초 감소",
      "'중격계' 대상 피해 10% 증가",
      "명중 시 항상 크리티컬",
      "'중격계' 대상 피해 20% 증가",
    ],
  },
  {
    id: "sword-10",
    name: "절단의 맹타",
    class: "검성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 100,
    range: 4,
    castTime: "즉시 시전",
    description: "시전자 주변 4m 내 최대 4명의 적에게 930-932 피해를 입히고 위협도를 증가시킵니다. 스킬 사용 중 막기 200 증가, 크리티컬 시 정신력 50 회복.",
    groggyGauge: 2,
    tags: ["발동기"],
    target: "시전자 주변 4인(적대)",
    specialization: [
      "정신력 소모량 20% 감소",
      "스킬 사용 중 막기 200 증가",
      "이동 가능 스킬로 변경",
      "명중 대상 수에 따라 최대 12%까지 피해 증가",
      "크리티컬 시 정신력 50 회복",
    ],
  },
  
  // 살성 스킬
  {
    id: "assassin-1",
    name: "퀵 컷",
    class: "살성",
    level: 20,
    type: "공격",
    cooldown: 10,
    mpCost: 200,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 내에 있는 최대 4명의 적에게 1216~1270의 피해를 입히고 정신력을 100 회복시킵니다.",
    target: "시전자 주변 4인(적대)",
  },
  {
    id: "assassin-2",
    name: "짐승의 포효",
    class: "살성",
    level: 20,
    type: "공격",
    cooldown: 10,
    mpCost: 150,
    range: 4,
    castTime: "즉시 시전",
    description: "반격 상태에서 사용 시 적에게 1623~1695의 피해를 입히고 '백탄 대검'을 1단계 적용합니다. 반격 상태가 아니어도 사용할 수 있습니다.",
    tags: ["약화"],
    target: "단일 대상(적대)",
  },
  {
    id: "assassin-3",
    name: "플래시",
    class: "살성",
    level: 20,
    type: "공격",
    cooldown: 12,
    mpCost: 180,
    range: 4,
    castTime: "즉시 시전",
    description: "4m 반경 내 최대 4명의 적에게 2626~2737의 피해를 입히고 4m 뒤로 물러나며, 50% 확률로 대상에게 출혈 효과를 남깁니다.",
    tags: ["약화"],
    target: "시전자 주변 4인(적대)",
  },
  {
    id: "assassin-4",
    name: "몰래 공격하다",
    class: "살성",
    level: 20,
    type: "공격",
    cooldown: 20,
    mpCost: 180,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 이내의 적에게 즉시 이동하여 2233~2332 피해를 입히고 75% 확률로 기절 상태를 부여합니다.",
    tags: ["약화"],
    target: "단일 대상(적대)",
  },
  {
    id: "assassin-5",
    name: "기습",
    class: "살성",
    level: 20,
    type: "공격",
    cooldown: 12,
    mpCost: 200,
    range: 4,
    castTime: "즉시 시전",
    description: "앞의 적에게 2394~3438 피해를 입히고, 후방에서 공격 시 4283~4470 피해를 입힙니다. 비급 게이지 감소량이 7 증가합니다.",
    target: "단일 대상(적대)",
  },
  {
    id: "assassin-6",
    name: "패턴 폭발",
    class: "살성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 이내의 대상을 향해 살성 패턴을 폭발시켜 3191~3323 피해를 입힙니다. 명중한 대상이 많을수록 피해가 증가하며, 마지막 폭발은 대상에게 스턴을 부여합니다.",
    tags: ["약화"],
    target: "대상 주변 4인(적대)",
  },
  {
    id: "assassin-7",
    name: "단검 던지기",
    class: "살성",
    level: 20,
    type: "공격",
    cooldown: 18,
    mpCost: 150,
    range: 20,
    castTime: "즉시 시전",
    description: "앞으로 2단 점프하며 대상에게 5433~5649 피해를 입히고, 5초 동안 대상의 이동 속도를 15% 감소시킵니다.",
    target: "단일 대상(적대)",
  },
  {
    id: "assassin-8",
    name: "나선형 슬래시",
    class: "살성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description: "몰이된 대상을 향해 7245~7533의 피해를 주고, 명중한 대상에게 출혈 효과를 적용합니다.",
    tags: ["약화"],
    target: "대상 주변 4인(적대)",
  },
  {
    id: "assassin-9",
    name: "에어 바인딩",
    class: "살성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 150,
    range: 10,
    castTime: "즉시 시전",
    description: "10m 반경 내 대상을 공중으로 띄우며 3621~3765의 피해를 입히고, 50% 확률로 5초간 공중 속박 상태를 유지합니다.",
    tags: ["약화"],
    target: "단일 대상(적대)",
  },
  {
    id: "assassin-10",
    name: "새도우 워크",
    class: "살성",
    level: 20,
    type: "버프",
    cooldown: 60,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "자신과 20m 반경 내 아군을 10초 동안 은신 상태로 만듭니다. 전투에 돌입하면 은신 효과는 해제되며 이동 속도가 20% 증가합니다.",
    tags: ["강화"],
    target: "시전자 주변 4인(파티원)",
  },

  // 수호성 스킬
  {
    id: "guardian-1",
    name: "맹렬한 일격",
    class: "수호성",
    level: 20,
    type: "공격",
    cooldown: 0,
    mpCost: 0,
    range: 4,
    castTime: "즉시 시전",
    description: "시전자 주변 4m 내 최대 4명의 적에게 559-560 피해를 입히고 위협도를 증가시킵니다. 정신력 100 회복. 논타겟 | 이동 가능.",
    groggyGauge: 0,
    tags: ["발동기", "논타겟", "이동 가능"],
    target: "시전자 주변 4인(적대)",
    specialization: [
      "정신력 회복량 20% 증가",
      "피해의 7%를 HP로 흡수",
      "명중 시 다중 타격 확률 50% 증가",
      "명중 시 [보호의 일격] 재시전 시간 1초 감소",
      "4타 연속 공격 [위협의 일격] 추가",
    ],
  },
  {
    id: "guardian-2",
    name: "연속 난타",
    class: "수호성",
    level: 20,
    type: "공격",
    cooldown: 0,
    mpCost: 0,
    range: 4,
    castTime: "즉시 시전",
    description: "시전자 주변 4m 내 최대 4명의 적에게 1200-1203 피해를 입히고 위협도를 증가시킵니다. 그로기 게이지 피해 2. 논타겟 | 이동 가능.",
    groggyGauge: 2,
    tags: ["발동기", "논타겟", "이동 가능"],
    target: "시전자 주변 4인(적대)",
    specialization: [
      "정신력 소모량 20% 감소",
      "[징벌의 일격] 피해의 15%를 HP로 흡수",
      "명중 대상 수에 따라 최대 12%까지 피해 증가",
      "[징벌의 일격] 명중 시 [징벌] 재시전 시간 22초 감소",
      "[징벌의 일격] 추가 발동 1회",
    ],
  },
  {
    id: "guardian-3",
    name: "포획",
    class: "수호성",
    level: 20,
    type: "디버프",
    cooldown: 15,
    mpCost: 100,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상에게 1170-1172 피해를 입히고 시전자 쪽으로 끌어당기며, 75% 확률로 2초간 속박합니다. 대상이 NPC인 경우 속박이 100% 성공합니다. 그로기 게이지 피해 10.",
    groggyGauge: 10,
    tags: [],
    target: "단일 대상(적대)",
    specialization: [
      "대상이 군중 제어 면역인 경우 대상으로 이동",
      "명중 시 5초간 명중률 200 감소",
      "적 처치 시 재시전 시간 초기화",
      "최대 HP의 10%에 해당하는 보호막 획득",
      "50% 확률로 3초간 기절",
    ],
  },
  {
    id: "guardian-4",
    name: "방패 강타",
    class: "수호성",
    level: 20,
    type: "공격",
    cooldown: 10,
    mpCost: 100,
    range: 4,
    castTime: "즉시 시전",
    description: "시전자 전방 4m 내 최대 4명의 적에게 2021-2024 피해를 입힙니다. 대상은 60% 확률로 3초간 기절합니다. 대상이 NPC인 경우 기절이 100% 성공합니다. 그로기 게이지 피해 10.",
    groggyGauge: 10,
    tags: ["약화"],
    target: "시전자 전방 4인(적대)",
    specialization: [
      "기절 지속 시간 1초 증가",
      "명중 시 정신력 소모 제거 및 정신력 200 회복",
      "50% 확률로 [약화의 일격] 발동",
      "재시전 시간 2초 감소",
      "광역 기절",
    ],
  },
  {
    id: "guardian-5",
    name: "보호의 일격",
    class: "수호성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 200,
    range: 4.5,
    castTime: "즉시 시전",
    description: "시전자 주변 5m 내 최대 4명의 적에게 1843-1846 피해를 입힙니다. 시전자는 즉시 1911-2102 HP를 회복하고 10초간 '보호' 효과를 획득합니다. [보호]: 피해 저항력 20% 증가. 논타겟.",
    groggyGauge: 0,
    tags: ["강화", "논타겟"],
    target: "시전자 주변 4인(적대)",
    specialization: [
      "보호 지속 시간 5초 증가",
      "보호 중 막기 100 증가",
      "보호 중 지속 회복 효과",
      "보호의 피해 저항력 효과가 명중 대상 수에 따라 증가",
      "스킬 사용 시 파티원 피해 저항력 20% 증가",
    ],
  },
  {
    id: "guardian-6",
    name: "징벌",
    class: "수호성",
    level: 20,
    type: "공격",
    cooldown: 30,
    mpCost: 200,
    range: 5,
    castTime: "0.5초/1초/1.5초",
    description: "시전자 주변 5m 내 최대 4명의 적에게 3559-5703 피해를 입힙니다. 최대 3단계 차지 스킬. 그로기 게이지 피해 15. 논타겟 | 차지 스킬.",
    groggyGauge: 15,
    tags: ["논타겟", "차지 스킬"],
    maxCharge: 3,
    target: "시전자 주변 4인(적대)",
    specialization: [
      "피해의 10%를 HP로 흡수",
      "명중 시 대상에게 지속 피해 적용",
      "스킬 속도 30% 증가",
      "이동 가능 스킬로 변경",
      "막기와 회피 무시, 다중 타격",
    ],
  },
  {
    id: "guardian-7",
    name: "주신의 징벌",
    class: "수호성",
    level: 20,
    type: "공격",
    element: "바람",
    cooldown: 60,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상 주변 4m 내 최대 4명의 적에게 2880-3297 피해를 입히고, 75% 확률로 3초간 기절시킵니다. 적은 10초간 이동 속도 감소 상태가 됩니다. 대상이 NPC인 경우 기절이 100% 성공합니다. 그로기 게이지 피해 75.",
    groggyGauge: 75,
    tags: ["약화"],
    target: "대상 주변 4인(적대)",
    specialization: [
      "명중 대상 수에 따라 최대 20%까지 피해 증가",
      "명중 시 10초간 이동 속도 40% 감소",
      "그로기 게이지 피해 25 증가",
      "기절 확률 25% 증가",
    ],
  },
  {
    id: "guardian-8",
    name: "전우 보호",
    class: "수호성",
    level: 20,
    type: "버프",
    cooldown: 120,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description: "10초간 40m 내 파티원이 공격받을 때마다 시전자가 피해의 21%를 받고, 공격받은 파티원은 피해의 21%를 받습니다. 전우 보호 중 [보호의 인] 패시브의 보호막 효과와 [고급 차단] 패시브의 피해 저항력 효과가 1.5배 증가합니다. HP가 25% 이하일 때 25% 회복. 전우 보호 종료 시 즉시 최대 HP의 50% 회복.",
    groggyGauge: 0,
    tags: [],
    target: "시전자 주변 4인(파티원)",
    specialization: [
      "HP 25% 이하일 때 피격 시 최대 HP의 25% 회복",
      "지속 시간 동안 [보호의 인] 패시브의 보호막 효과 1.5배 증가",
      "지속 시간 동안 [고급 차단] 패시브의 피해 저항력 효과 1.5배 증가",
      "효과 종료 시 최대 HP의 50% 즉시 회복",
    ],
  },
  {
    id: "guardian-9",
    name: "이중 갑옷",
    class: "수호성",
    level: 20,
    type: "버프",
    cooldown: 90,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "20초간 피해 저항력 50% 증가, 모든 속성 저항력 10% 증가. 이중 갑옷 중 5m 내 받는 피해의 10%를 반사합니다. [철벽 방어]의 방어력 효과가 1.5배 증가합니다. 이동 가능.",
    groggyGauge: 0,
    tags: ["이동 가능"],
    target: "시전자",
    specialization: [
      "모든 속성 저항력 10% 증가",
      "5m 내 받는 피해의 10% 반사",
      "지속 시간 동안 [철벽 방어]의 방어력 효과 1.5배 증가",
      "추가 피해 저항력 20% 증가",
    ],
  },
  {
    id: "guardian-10",
    name: "보호의 방패",
    class: "수호성",
    level: 20,
    type: "방어",
    cooldown: 20,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "짧은 시간 동안 전방 공격에 대한 막기 피해 감소가 100% 증가하고 막기를 보장합니다. 최대 3회 연속 시전 가능. 막기 성공 시 정신력 300, 행동력 회복 및 HP 10% 1회 회복. 지속 스킬 | 이동 가능.",
    groggyGauge: 0,
    tags: ["지속 스킬", "이동 가능"],
    target: "시전자",
    specialization: [
      "연속 시전 +1회",
      "이동 가능 스킬로 변경",
      "연속 시전 +1회",
      "막기 성공 시 HP 10% 1회 회복",
    ],
  },

  // 마도성 스킬 (이미지 기반)
  {
    id: "mage-1",
    name: "집중의 기원",
    class: "마도성",
    level: 12,
    type: "강화",
    cooldown: 0,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "15.5초간 자신의 공격력 10% 증가, 명중률 100 증가, 전투 속도 10% 증가, 스킬 사용 정신력 소모량 10% 감소.",
    groggyGauge: 0,
    tags: ["논타겟", "이동 가능"],
    target: "시전자",
    specialization: [
      "스킬 정신력 소모량 10% 감소",
      "공격력 5% 증가",
      "최대 정신력 500 증가",
      "전투 속도 10% 증가",
      "모든 스킬 재시전 시간 10초 감소",
    ],
  },
  {
    id: "mage-2",
    name: "불꽃 화살",
    class: "마도성",
    level: 12,
    type: "공격",
    element: "불",
    cooldown: 0,
    mpCost: 0,
    range: 20,
    castTime: 0,
    description: "20m 내 대상에게 594~595 불 속성 피해를 입히고 정신력 120 회복.",
    groggyGauge: 0,
    tags: ["이동 가능"],
    target: "단일 대상(적대)",
    specialization: [
      "정신력 회복량 20% 증가",
      "피해의 7%를 HP로 흡수",
      "명중 시 다중 타격 확률 50%",
      "[열화] 명중 시 5초간 불 표식 적용",
      "[얼화] 명중 시 [불꽃 폭발] 재시전 시간 초기화",
    ],
  },
  {
    id: "mage-3",
    name: "얼음 사슬",
    class: "마도성",
    level: 12,
    type: "공격",
    element: "물",
    cooldown: 0,
    mpCost: 0,
    range: 20,
    castTime: 0,
    description: "20m 내 대상 주변 4m 내 최대 4명의 적에게 784~785 물 속성 피해를 입히고 이동 속도 40% 감소(5초) 상태를 적용합니다. 명중 시 [겨울의 속박] 재시전 시간 1초 감소.",
    groggyGauge: 2,
    tags: ["발동기", "약화", "이동 가능"],
    target: "대상 주변 4인(적대)",
    specialization: [
      "정신력 소모량 20% 감소",
      "이동 속도 감소 지속 시간 2초 증가",
      "명중 대상 수에 따라 최대 12%까지 피해 증가",
      "명중 시 [겨울의 속박] 재시전 시간 1초 감소",
      "[냉기 파동] 명중 시 5% 확률로 2초간 방어력 감소 적용",
    ],
  },
  {
    id: "mage-4",
    name: "불꽃 작살",
    class: "마도성",
    level: 12,
    type: "공격",
    element: "불",
    cooldown: 5,
    mpCost: 250,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상에게 1515~1520 불 속성 피해를 입힙니다. 스킬 속도 20% 증가, [지옥의 화염] 재시전 시간 작살 명중당 1초 감소.",
    groggyGauge: 5,
    tags: [],
    target: "단일 대상(적대)",
    specialization: [
      "정신력 소모량 50% 감소",
      "스킬 속도 20% 증가",
      "이동 가능 스킬로 변경",
      "[지옥의 화염] 재시전 시간 작살 명중당 1초 감소",
      "작살 피해 10% 증가",
    ],
  },
  {
    id: "mage-5",
    name: "혹한의 바람",
    class: "마도성",
    level: 12,
    type: "공격",
    element: "물",
    cooldown: 20,
    mpCost: 150,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상 위치에 3초간 지속되는 혹한의 바람을 소환합니다. 혹한의 바람은 자신을 중심으로 4m 내 최대 4명의 적을 끌어당기며 1512~1512 물 속성 피해를 입힙니다. 적은 30% 확률로 3초간 속박됩니다. 대상이 NPC인 경우 속박이 100% 성공합니다.",
    groggyGauge: 10,
    tags: [],
    target: "대상 주변 4인(적대)",
    specialization: [
      "[혹한의 바람] 소환 지속 시간 1초 증가",
      "3초간 물 속성 저항력 15% 감소",
      "끌어당김 효과",
      "막기와 회피 무시, 다중 타격",
      "최종 타격 시 25% 확률로 2초간 빙결",
    ],
  },
  {
    id: "mage-6",
    name: "루미엘의 공간",
    class: "마도성",
    level: 12,
    type: "공격",
    cooldown: 120,
    mpCost: 300,
    range: 5,
    castTime: "즉시 시전",
    description: "시전자 주변 5m 내 최대 4명의 적에게 1923~2200 피해를 입히고 75% 확률로 3초간 공중 속박 상태를 적용합니다. 대상이 NPC인 경우 공중 속박이 100% 성공합니다.",
    groggyGauge: 0,
    tags: ["논타겟"],
    target: "시전자 주변 4인(적대)",
    specialization: [
      "명중 대상 수에 따라 최대 20%까지 피해 증가",
      "[나락] 연속 타격 2회 추가",
      "[나락] 눕힘 지속 시간 1초 증가",
      "[루미엘의 공간] 재시전 시간 30초 감소",
    ],
  },
  {
    id: "mage-7",
    name: "겨울의 속박",
    class: "마도성",
    level: 12,
    type: "공격",
    element: "물",
    cooldown: 45,
    mpCost: 200,
    range: 4,
    castTime: "즉시 시전",
    description: "시전자 주변 5m 내 최대 4명의 적에게 1641~1642 물 속성 피해를 입히고 3초간 이동 속도 감소 상태를 적용합니다. 적은 30% 확률로 3초간 빙결됩니다. 대상이 NPC인 경우 빙결이 100% 성공합니다.",
    groggyGauge: 0,
    tags: ["발동기", "약화", "논타겟"],
    target: "시전자 주변 4인(적대)",
    specialization: [
      "[겨울의 속박] 이동 속도 감소 지속 시간 2초 증가",
      "[겨울의 속박] 명중 시 30% 확률로 3초간 빙결",
      "[겨울의 속박] 명중 시 5초간 피해 저항력 20% 감소",
      "[겨울의 환영] 연속 타격 2회 추가",
      "[겨울의 속박] 재시전 시간 15초 감소",
    ],
  },
  {
    id: "mage-8",
    name: "지옥의 화염",
    class: "마도성",
    level: 12,
    type: "공격",
    element: "불",
    cooldown: 45,
    mpCost: 200,
    range: 20,
    castTime: "0.5초/1초/1.5초",
    description: "20m 내 대상에게 2498~3998 불 속성 피해를 입힙니다. 최대 차지 시 막기와 회피 무시, 다중 타격하며 대상 위치에 5초간 지속되는 화염 지대를 소환합니다. 화염 지대: 화염 지대 내 최대 4명의 적에게 735~735 피해.",
    groggyGauge: 20,
    tags: ["차지 스킬"],
    maxCharge: 3,
    target: "단일 대상(적대)",
    specialization: [
      "최대 차지 시 불 표식 적용",
      "최대 차지 시 화염 지대 소환",
      "이동 가능 스킬로 변경",
      "최대 차지 시 막기와 회피 무시, 다중 타격",
      "재시전 시간 15초 감소",
    ],
  },
  {
    id: "mage-9",
    name: "지연 폭발",
    class: "마도성",
    level: 12,
    type: "공격",
    element: "불",
    cooldown: 20,
    mpCost: 0,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상에게 4초 후 2663~2665 불 속성 피해를 입힙니다. 지연 시간 동안 대상의 피해 저항력 20% 감소. 정신력 200 회복.",
    groggyGauge: 0,
    tags: ["약화", "이동 가능"],
    target: "단일 대상(적대)",
    specialization: [
      "정신력 200 회복",
      "[지연 폭발] 재시전 시간 10초 감소",
      "광역 스킬로 변경",
      "추가 피해 저항력 감소",
    ],
  },
  {
    id: "mage-10",
    name: "빙하 강타",
    class: "마도성",
    level: 12,
    type: "공격",
    element: "물",
    cooldown: 60,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상 주변 4m 내 최대 4명의 적에게 3699~4231 물 속성 피해를 입힙니다.",
    groggyGauge: 20,
    tags: ["약화"],
    target: "대상 주변 4인(적대)",
    specialization: [
      "명중 대상 수에 따라 최대 20%까지 피해 증가",
      "재시전 시간 30초 감소",
      "30% 확률로 3초간 마비",
      "막기와 회피 무시, 다중 타격",
    ],
  },
  {
    id: "mage-11",
    name: "영혼 동결",
    class: "마도성",
    level: 12,
    type: "공격",
    element: "물",
    cooldown: 60,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상에게 2472~2474 물 속성 피해를 입히고 75% 확률로 5초간 봉인 상태를 적용합니다. 대상은 50% 확률로 5초간 속박되며 이동 속도 1000 감소합니다. 대상이 NPC인 경우 봉인과 속박이 100% 성공합니다.",
    groggyGauge: 20,
    tags: ["약화"],
    target: "단일 대상(적대)",
    specialization: [
      "50% 확률로 5초간 속박 효과 적용",
      "이동 속도 1000 감소",
      "봉인 지속 시간 2초 증가",
      "봉인 확률 25% 증가",
    ],
  },

  // 치유성 스킬 (호법성 이미지 기반)
  {
    id: "healer-1",
    name: "대지의 응보",
    class: "치유성",
    level: 20,
    type: "공격",
    element: "땅",
    cooldown: 0,
    mpCost: 0,
    range: 20,
    castTime: 0,
    description: "20m 내 대상에게 503-504 땅 속성 피해를 입히고 정신력 110 회복. 이동 가능.",
    groggyGauge: 0,
    tags: ["이동 가능"],
    target: "단일 대상(적대)",
    specialization: [
      "정신력 회복량 20% 증가",
      "[방전] 연속 스킬 발동 확률 15% 증가",
      "명중 시 다중 타격 확률 50% 증가",
      "[방전] 명중 시 [학식] 재시전 시간 7초 감소",
      "[방전] 광역 스킬로 변경",
    ],
  },
  {
    id: "healer-2",
    name: "심판의 번개",
    class: "치유성",
    level: 20,
    type: "공격",
    element: "바람",
    cooldown: 0,
    mpCost: 0,
    range: 20,
    castTime: 0,
    description: "20m 내 대상 주변 4m 내 최대 4명의 적에게 807-808 바람 속성 피해를 입힙니다. 그로기 게이지 피해 2. 이동 가능.",
    groggyGauge: 2,
    tags: ["이동 가능"],
    target: "대상 주변 4인(적대)",
    specialization: [
      "정신력 소모량 20% 감소",
      "명중 대상 수가 감소할수록 최대 12%까지 피해 증가",
      "[전술] 명중 시 5초간 전투 속도 10% 증가",
      "[징벌] 명중 시 10% 확률로 2초간",
      "[징벌] 추가 팀 1개",
    ],
  },
  {
    id: "healer-3",
    name: "약화의 낙인",
    class: "치유성",
    level: 20,
    type: "공격",
    element: "바람",
    cooldown: 10,
    mpCost: 100,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상 주변 4m 내 최대 4명의 적에게 946-947 바람 속성 피해를 입히고 적의 바람 속성 저항력 10% 감소(10초), 1초마다 123 지속 피해를 10초간 입힙니다. 그로기 게이지 피해 10.",
    groggyGauge: 10,
    tags: ["약화"],
    target: "대상 주변 4인(적대)",
    specialization: [
      "정신력 소모 제거 및 정신력 150 회복",
      "방어력 10% 감소",
      "20% 확률로 3초간 기절",
      "[약화의 낙인] 효과가 모든 속성 저항력 감소로 변경",
      "지속 피해 간격 50% 감소",
    ],
  },
  {
    id: "healer-4",
    name: "신성한 기운",
    class: "치유성",
    level: 20,
    type: "소환",
    cooldown: 30,
    mpCost: 0,
    range: 20,
    castTime: 0,
    description: "시전자 근처에 신성한 기운을 소환합니다. 기운은 이동하지 않으며 시전자가 지정한 20m 내 대상을 정기적으로 공격하여 214 땅 속성 피해를 입힙니다. 기운은 10초간 지속되며 명중할 때마다 시전자의 HP를 소모합니다.",
    groggyGauge: 0,
    tags: [],
    target: "단일 대상(적대)",
    specialization: [
      "기운 주변 최대 4명의 대상 이동 속도 3 증가",
      "광역 스킬로 변경",
      "[신성한 기운] 투사체 속도 100% 증가",
      "[신성한 기운] 지속 시간 3초 증가",
      "재시전 시간 5초 감소",
    ],
  },
  {
    id: "healer-5",
    name: "쾌유의 광휘",
    class: "치유성",
    level: 20,
    type: "회복",
    cooldown: 8,
    mpCost: 0,
    range: 25,
    castTime: 0.5,
    description: "시전자와 25m 내 파티원의 HP를 1742-1916 회복합니다. 최대 차지: 2612-2873 HP 회복. 최대 1단계 차지 스킬, 논타겟 스킬 | 차지 스킬.",
    groggyGauge: 0,
    tags: ["논타겟", "차지 스킬"],
    maxCharge: 1,
    target: "시전자 주변 4인(파티원)",
    specialization: [
      "최대 차지 시 최대 2개의 디버프 제거",
      "스킬 속도 20% 증가",
      "이동 가능 스킬 트리로 변경",
      "최대 차지 시 10초간 받는 회복량 20% 증가",
      "최대 차지 시 최대 HP의 10% 회복",
    ],
  },
  {
    id: "healer-6",
    name: "벽력",
    class: "치유성",
    level: 20,
    type: "공격",
    element: "바람",
    cooldown: 45,
    mpCost: 300,
    range: 20,
    castTime: "0.5초/1초/1.5초",
    description: "20m 내 대상 주변 4m 내 최대 4명의 적에게 2768-4434 바람 속성 피해를 입힙니다. 최대 3단계 차지 스킬, 차지 스킬. 그로기 게이지 피해 20.",
    groggyGauge: 20,
    tags: ["차지 스킬"],
    maxCharge: 3,
    target: "대상 주변 4인(적대)",
    specialization: [
      "최대 차지 시 30% 확률로 3초간 기절",
      "이동 가능 스킬로 변경",
      "스킬 속도 30% 증가",
      "명중 대상 수가 증가할수록 최대 20%까지 피해 증가",
      "[벽력] 적 처치 시 [벽력] 재시전 시간 초기화",
    ],
  },
  {
    id: "healer-7",
    name: "권능 폭발",
    class: "치유성",
    level: 20,
    type: "공격",
    element: "땅",
    cooldown: 60,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상에게 3383-3387 땅 속성 피해를 입히고 75% 확률로 밀쳐내며 기절시킵니다. 스킬 속도 20% 증가, 명중 시 보장된 크리티컬 피해로 명중합니다. 대상이 NPC인 경우 기절이 100% 확률로 적용됩니다. 그로기 게이지 피해 50.",
    groggyGauge: 50,
    tags: ["약화"],
    target: "단일 대상(적대)",
    specialization: [
      "스킬 속도 20% 증가",
      "명중 시 보장된 크리티컬",
      "75% 확률로 밀쳐냄",
      "75% 확률로 3초간 기절",
    ],
  },
  {
    id: "healer-8",
    name: "파멸의 목소리",
    class: "치유성",
    level: 20,
    type: "공격",
    element: "땅",
    cooldown: 90,
    mpCost: 200,
    range: 20,
    castTime: "즉시 시전",
    description: "20m 내 대상 주변 4m 내 최대 4명의 적에게 3387-3876 땅 속성 피해를 입히고 보호막을 제거합니다. 적은 10초간 0.5초마다 419 피해를 받으며 받는 회복량이 80% 감소합니다.",
    groggyGauge: 0,
    tags: ["약화"],
    target: "대상 주변 4인(적대)",
    specialization: [
      "명중 대상 수가 증가할수록 최대 20%까지 피해 증가",
      "명중 시 보호막 제거",
      "받는 회복량 추가 20% 감소",
      "지속 피해 간격 50% 감소",
    ],
  },
  {
    id: "healer-9",
    name: "면죄",
    class: "치유성",
    level: 20,
    type: "회복",
    cooldown: 60,
    mpCost: 0,
    range: 25,
    castTime: "즉시 시전",
    description: "시전자와 25m 내 파티원의 모든 디버프를 제거하고 5883-6471 HP를 회복합니다. 시전자와 최저 HP 파티원은 추가로 최대 HP의 10%를 회복합니다. 논타겟 스킬.",
    groggyGauge: 0,
    tags: ["논타겟"],
    target: "시전자 주변 4인(파티원)",
    specialization: [
      "재시전 시간 30초 감소",
      "최대 5개의 디버프 제거",
      "시전자와 최저 HP 파티원 최대 HP의 10% 회복",
      "모든 디버프 제거",
    ],
  },
  {
    id: "healer-10",
    name: "치유의 기운",
    class: "치유성",
    level: 20,
    type: "소환",
    cooldown: 60,
    mpCost: 0,
    range: 0,
    castTime: "즉시 시전",
    description: "시전자 근처에 15초간 지속되는 치유의 기운을 소환합니다. 기운은 이동하지 않으며 시전자와 10m 내 파티원을 정기적으로 회복시켜 701-841 HP를 회복하고 방어력 10%, 공격력 10%, 전투 속도 10% 증가 효과를 부여합니다. 논타겟 스킬.",
    groggyGauge: 0,
    tags: ["회복", "논타겟"],
    target: "시전자 주변 4인(파티원)",
    specialization: [
      "[치유의 기운] 회복 범위 3m 증가",
      "방어력 10% 증가",
      "공격력 10% 증가",
      "전투 속도 10% 증가",
    ],
  },
];

/**
 * 아이템 더미 데이터
 */
export const dummyItems: Item[] = [
  {
    id: "1",
    name: "천둥의 검",
    type: "weapon",
    grade: "legendary",
    description: "천둥의 힘을 담은 전설의 검. 높은 공격력을 제공합니다.",
    stats: {
      attack: 285,
      accuracy: 120,
    },
  },
  {
    id: "2",
    name: "용의 가죽 갑옷",
    type: "armor",
    grade: "epic",
    description: "용의 가죽으로 만든 강력한 방어구.",
    stats: {
      defense: 195,
      hp: 850,
    },
  },
  {
    id: "3",
    name: "마력의 목걸이",
    type: "accessory",
    grade: "epic",
    description: "마법 공격력을 크게 향상시키는 액세서리.",
    stats: {
      attack: 95,
      mp: 420,
    },
  },
  {
    id: "4",
    name: "회복 물약",
    type: "consumable",
    grade: "common",
    description: "HP를 500 회복시킵니다.",
    stats: {
      hp: 500,
    },
  },
  {
    id: "5",
    name: "정신력 물약",
    type: "consumable",
    grade: "common",
    description: "MP를 300 회복시킵니다.",
    stats: {
      mp: 300,
    },
  },
  {
    id: "6",
    name: "영웅의 투구",
    type: "armor",
    grade: "legendary",
    description: "전설의 영웅이 착용했던 투구. 강력한 방어력을 제공합니다.",
    stats: {
      defense: 145,
      hp: 650,
      accuracy: 85,
    },
  },
  {
    id: "7",
    name: "마법 지팡이",
    type: "weapon",
    grade: "epic",
    description: "마법사용 지팡이. 마법 공격력이 크게 향상됩니다.",
    stats: {
      attack: 265,
      mp: 380,
    },
  },
  {
    id: "8",
    name: "민첩의 반지",
    type: "accessory",
    grade: "rare",
    description: "민첩성을 향상시키는 반지.",
    stats: {
      evasion: 180,
      accuracy: 95,
    },
  },
  {
    id: "9",
    name: "철광석",
    type: "material",
    grade: "common",
    description: "장비 제작에 사용되는 기본 재료.",
  },
  {
    id: "10",
    name: "정화의 물약",
    type: "consumable",
    grade: "uncommon",
    description: "모든 상태이상을 제거합니다.",
  },
];

/**
 * 가이드 더미 데이터
 */
export const dummyGuides = [
  {
    id: "1",
    title: "초보자 가이드",
    category: "시작하기",
    content: "아이온2를 처음 시작하는 분들을 위한 기본 가이드입니다.",
    thumbnail: "/images/guide-beginner.jpg",
  },
  {
    id: "2",
    title: "직업 선택 가이드",
    category: "캐릭터",
    content: "각 직업의 특징과 추천 직업을 안내합니다.",
    thumbnail: "/images/guide-class.jpg",
  },
  {
    id: "3",
    title: "장비 강화 가이드",
    category: "아이템",
    content: "장비 강화 방법과 최적의 타이밍을 설명합니다.",
    thumbnail: "/images/guide-enhance.jpg",
  },
  {
    id: "4",
    title: "던전 공략 가이드",
    category: "던전",
    content: "주요 던전의 공략 방법과 보상 정보를 제공합니다.",
    thumbnail: "/images/guide-dungeon.jpg",
  },
  {
    id: "5",
    title: "PvP 전투 가이드",
    category: "PvP",
    content: "플레이어 간 전투에서 승리하는 전략을 소개합니다.",
    thumbnail: "/images/guide-pvp.jpg",
  },
];
